name: Fetch CI Nightly Data
run-name: Fetch CI Nightly Data
on:
  schedule:
    - cron: '0 * * * *'
  push:
jobs:
  fetch-and-commit-data:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Update dashboard data
      run: |
        mkdir -p data
        node js/fetch-ci-nightly-data.js > data/job_stats.json

        git config user.name "GH Actions Workflow"
        git config user.email "gha@runner"

        git add data/job_stats.json
        git commit -m "[skip ci] latest ci nightly data" || echo "No changes"
        git push

